"use client";
import { useMemo, useState } from "react";
type Mood="Poetic"|"Modern"|"Serene";
type Surname={hanzi:string;pinyin:string;tone:number;origin:string;keys:string[]};
const surnames:Surname[]=[
{hanzi:"\u8d75",pinyin:"Zhao",tone:4,origin:"A principal tradition traces Zhao to the Ying clan and the fief of Zhao; descendants adopted the place name.",keys:["z"]},{hanzi:"\u674e",pinyin:"Li",tone:3,origin:"Several traditions exist. A major account connects Li with an ancient judicial office, later written with the character for plum.",keys:["l"]},{hanzi:"\u738b",pinyin:"Wang",tone:2,origin:"A multi-origin surname, often linked to royal association and to Ji, Gui, and Zi clan traditions.",keys:["w"]},{hanzi:"\u9648",pinyin:"Chen",tone:2,origin:"A major tradition links Chen to the Gui clan and the ancient State of Chen.",keys:["c"]},{hanzi:"\u5f20",pinyin:"Zhang",tone:1,origin:"Traditional accounts connect Zhang with the ancient Ji clan and an early bow-making lineage.",keys:["zh"]},{hanzi:"\u6797",pinyin:"Lin",tone:2,origin:"Lin means forest. Traditional lineage accounts connect it with the descendants of Bi Gan.",keys:["r","li"]},{hanzi:"\u5468",pinyin:"Zhou",tone:1,origin:"Commonly linked to descendants of the Zhou royal house who adopted the state name.",keys:["j"]},{hanzi:"\u6768",pinyin:"Yang",tone:2,origin:"A major tradition links Yang to the Ji clan and the ancient place name Yang.",keys:["y"]},{hanzi:"\u9ec4",pinyin:"Huang",tone:2,origin:"A major origin tradition connects Huang with the ancient State of Huang.",keys:["h"]},{hanzi:"\u5434",pinyin:"Wu",tone:2,origin:"A principal tradition traces Wu to the Ji clan and the ancient State of Wu.",keys:["u"]}];
const first:[[string,string,number],...[string,string,number][]]=[["\u5b89","Ān",1],["\u5b81","Níng",2],["\u77e5","Zhī",1],["\u6e05","Qīng",1],["\u660e","Míng",2],["\u4e66","Shū",1],["\u666f","Jǐng",3],["\u662d","Zhāo",1],["\u4e91","Yún",2],["\u6708","Yuè",4],["\u661f","Xīng",1],["\u4e88","Yǔ",3],["\u5e0c","Xī",1],["\u5609","Jiā",1],["\u5ff5","Niàn",4],["\u9038","Yì",4],["\u9759","Jìng",4],["\u601d","Sī",1],["\u6000","Huái",2],["\u82e5","Ruò",4],["\u747e","Jǐn",3],["\u7389","Yù",4],["\u8bd7","Shī",1],["\u4ee4","Lìng",4],["\u627f","Chéng",2],["\u4fee","Xiū",1],["\u8212","Shū",1],["\u548c","Hé",2],["\u4e50","Lè",4],["\u6c90","Mù",4],["\u521d","Chū",1],["\u7136","Rán",2],["\u96c5","Yǎ",3],["\u5fc3","Xīn",1],["\u8a00","Yán",2],["\u5b65","Yòu",4],["\u6668","Chén",2],["\u6615","Xīn",1],["\u6f84","Chéng",2],["\u5b9b","Wǎn",3]];
const last:[[string,string,number],...[string,string,number][]]=[["\u5b89","Ān",1],["\u8fdc","Yuǎn",3],["\u664f","Yàn",4],["\u6f88","Chè",4],["\u6db5","Hán",2],["\u884c","Xíng",2],["\u7136","Rán",2],["\u8212","Shū",1],["\u534e","Huá",2],["\u6cb3","Hé",2],["\u8a00","Yán",2],["\u79be","Hé",2],["\u771f","Zhēn",1],["\u821f","Zhōu",1],["\u96c5","Yǎ",3],["\u6e90","Yuán",2],["\u5fc3","Xīn",1],["\u6600","Yún",2],["\u8fb0","Chén",2],["\u6c50","Xī",1],["\u7476","Yáo",2],["\u73e9","Héng",2],["\u97f5","Yùn",4],["\u6b4c","Gē",1],["\u5bb8","Chén",2]];
const meanings=["peace and clarity","a calm, far-reaching spirit","learning and quiet strength","brightness and natural ease","poetry and elegant rhythm","jade-like virtue and harmony","dawn and a generous heart","a clear mind and a steady path"];
const classical=[["\u968f\u98ce\u6f5c\u5165\u591c\uff0c\u6da6\u7269\u7ec6\u65e0\u58f0\u3002","It enters with the night wind, nourishing all things without a sound."],["\u7a7a\u5c71\u65b0\u96e8\u540e\uff0c\u5929\u6c14\u665a\u6765\u79cb\u3002","After fresh rain on an empty mountain, evening brings autumn air."],["\u4f46\u613f\u4eba\u957f\u4e45\uff0c\u5343\u91cc\u5171\u5a75\u5a1f\u3002","May we share the beauty of the moon, though far apart."]];
const tones:Record<Mood,string>={Poetic:"1 - 2",Modern:"2 - 4",Serene:"1 - 1"};
export default function Home(){const[familyName,setFamilyName]=useState("");const[style,setStyle]=useState<Mood>("Poetic");const[index,setIndex]=useState(0);const[active,setActive]=useState(false);const[reportOpen,setReportOpen]=useState(false);
const candidates=useMemo(()=>first.flatMap((a,i)=>last.map((b,j)=>({hanzi:a[0]+b[0],pinyin:`${a[1]} ${b[1]}`,tones:`${a[2]} - ${b[2]}`,meaning:meanings[(i+j)%meanings.length]}))),[]);
const make=()=>{setIndex(Math.floor(Math.random()*candidates.length));setActive(true);setReportOpen(false)};const surname=surnames.find(s=>s.keys.some(k=>familyName.trim().toLowerCase().startsWith(k)))??surnames[index%surnames.length];const given=candidates[index%candidates.length];const quote=classical[index%classical.length];
const drawCard=async(share=false)=>{const canvas=document.createElement("canvas");
canvas.width=1080;canvas.height=1080;const c=canvas.getContext("2d");if(!c)return;
c.fillStyle="#102033";c.fillRect(0,0,1080,1080);c.strokeStyle="#d7b472";c.lineWidth=9;c.strokeRect(48,48,984,984);c.strokeStyle="#a83227";c.lineWidth=2;c.strokeRect(70,70,940,940);
const flower=(x:number,y:number)=>{c.save();c.translate(x,y);for(let i=0;i<8;i++){c.rotate(Math.PI/4);c.fillStyle=i%2?"#b23b31":"#d7b472";c.beginPath();c.ellipse(0,-48,25,52,0,0,Math.PI*2);c.fill()}c.fillStyle="#f4e5be";c.beginPath();c.arc(0,0,19,0,Math.PI*2);c.fill();c.restore()};flower(145,145);flower(935,145);flower(145,935);flower(935,935);
c.fillStyle="#f6eee0";c.font="600 24px serif";c.textAlign="center";c.fillText("MINGZI / CHINESE NAME ATELIER",540,265);c.font="165px serif";c.fillText(surname.hanzi+given.hanzi,540,515);c.fillStyle="#d7b472";c.font="38px serif";c.fillText(`${surname.pinyin} ${given.pinyin}`,540,590);c.fillStyle="#f6eee0";c.font="25px sans-serif";c.fillText(given.meaning.toUpperCase(),540,666);c.fillStyle="#d6c9b6";c.font="27px serif";c.fillText(quote[1],540,808);c.font="20px sans-serif";c.fillText("A name, considered.",540,902);
const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/png"));
if(!blob)return;
const file=new File([blob],"my-mingzi-name-card.png",{type:"image/png"});
if(share&&navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"My Chinese name",text:`My Chinese name is ${surname.pinyin} ${given.pinyin}.`,files:[file]});
return;
}const link=document.createElement("a");
link.href=URL.createObjectURL(blob);
link.download=file.name;
link.click();
URL.revokeObjectURL(link.href)};const pageUrl=typeof window==="undefined"?"":window.location.href;
const shareText=encodeURIComponent(`My Chinese name is ${surname.pinyin} ${given.pinyin} — created with MINGZI.`);
return <main><nav className="nav"><a className="brand" href="#top">MINGZI<span>{"\u540d"}</span></a><div className="nav-links"><a href="#create">Name atelier</a><a href="/library">Library</a></div><button className="language">EN</button></nav><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">A name, considered</p><h1>Find a Chinese name<br/>with <em>meaning.</em></h1><p className="intro">A living name library of 1,000 candidate names, paired with Chinese surname stories and classical poetry.</p><a className="text-link" href="#create">Create your name <span>down</span></a></div><div className="seal-wrap"><div className="seal-shadow"/><div className="seal"><span>{"\u540d"}</span><small>ming</small></div><p>Every name<br/>begins with a story.</p></div></section><section className="maker" id="create"><div className="section-label">01 - Name atelier</div><div className="maker-grid"><div><h2>Begin with<br/>your surname.</h2><p>We match a Chinese surname, then choose a given name for sound, meaning, and cultural resonance.</p></div><div className="form-card"><label>Your family name <span>optional</span><input value={familyName} onChange={e=>setFamilyName(e.target.value)} placeholder="e.g. Smith"/></label><fieldset><legend>What speaks to you?</legend><div className="style-pills">{(["Poetic","Modern","Serene"]as const).map(x=><button key={x} className={style===x?"active":""} onClick={()=>setStyle(x)} type="button">{x}</button>)}</div></fieldset><button className="generate" type="button" onClick={make}>Match my Chinese name <span>go</span></button></div></div></section>{active&&<section className="result"><div className="result-top"><p className="eyebrow">Your complete Chinese name</p><button className="quiet-button" onClick={make}>Try another</button></div><div className="result-grid"><div className="name-art"><div className="brush-ring"/><p>{surname.pinyin} {given.pinyin}</p><strong>{surname.hanzi}{given.hanzi}</strong>
<small>{given.tones}</small>
</div><div className="reading"><h2>{surname.pinyin} {given.pinyin}</h2><h3>{given.meaning}</h3><p>Built from two name characters selected from the current 1,000-name candidate library.</p><div className="origin"><span>CHARACTER BREAKDOWN</span><p>{given.meaning}</p></div></div></div><div className="surname-story"><div><p className="eyebrow">Surname - {surname.hanzi} / {surname.pinyin}</p><h3>The story of {surname.pinyin}.</h3><p>{surname.origin}</p><div className="rhythm"><span>THE RHYTHM</span><p>The tonal pattern 
<b>{given.tones}</b>
 gives the full name a clear, changing cadence.</p></div></div><blockquote><span>CLASSICAL ECHO</span><p>{quote[0]}</p><cite>{quote[1]}</cite></blockquote></div><section className="name-card"><div className="name-card-art"><p>MINGZI / CHINESE NAME ATELIER</p><strong>{surname.hanzi}{given.hanzi}</strong><span>{surname.pinyin} {given.pinyin}</span><i>{given.meaning}</i></div><div className="card-copy"><p className="eyebrow">Your shareable name card</p><h3>Made to keep.<br/>Made to share.</h3><p>Save your name as a high-quality image, then post it wherever you like.</p><button onClick={()=>drawCard(false)}>Download name card</button><button className="native-share" onClick={()=>drawCard(true)}>Share from this device</button><div className="socials"><a href={`https://twitter.com/intent/tweet?text=${shareText}&url=${encodeURIComponent(pageUrl)}`} target="_blank" rel="noreferrer">X</a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(pageUrl)}`} target="_blank" rel="noreferrer">Facebook</a><a href="https://www.instagram.com/" onClick={()=>drawCard(false)} target="_blank" rel="noreferrer">Instagram</a><a href="https://www.tiktok.com/upload" onClick={()=>drawCard(false)} target="_blank" rel="noreferrer">TikTok</a></div><small>Instagram and TikTok will open after the card downloads, ready for you to upload it.</small></div></section><section className="report-invite"><p className="eyebrow">Go deeper</p><h3>Would you like a detailed name report?</h3><p>Explore a more considered reading of your name’s characters, sound, surname story, and cultural echoes.</p><button type="button" onClick={()=>setReportOpen(true)}>Explore the detailed report</button>{reportOpen&&<div className="report-reveal" role="status"><strong>Coming soon</strong><p>A detailed cultural and language report is being prepared. No payment is requested today.</p></div>}</section><p className="disclaimer">MINGZI offers cultural and linguistic inspiration for personal exploration. It does not provide medical, legal, financial, or life-decision advice.</p></section>}<section className="principles"><div className="section-label">02 - The art of naming</div><div className="principle-grid"><article><b>{"\u58f0"}</b><h3>Sound</h3><p>A surname leads. The given name follows with balance and ease.</p></article><article><b>{"\u5f62"}</b><h3>Character</h3><p>Every character holds an image as well as a sound.</p></article><article><b>{"\u610f"}</b><h3>Meaning</h3><p>The name carries a story the wearer can make their own.</p></article></div></section><footer><a className="brand" href="#top">MINGZI<span>{"\u540d"}</span></a><p>Chinese names, thoughtfully made.</p><span>Copyright 2026 MINGZI</span></footer></main>}
